"""Initial migration

Revision ID: 081628d7948e
Revises: 
Create Date: 2024-08-07 11:26:37.960167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081628d7948e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channelId', sa.String(length=255), nullable=False),
    sa.Column('channelLink', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channelId')
    )
    op.create_table('tweet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tweetId', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tweetPictureLink', sa.Text(), nullable=True),
    sa.Column('tweetVideoLink', sa.Text(), nullable=True),
    sa.Column('tweetLink', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('replyToTweetId', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Sent', 'Failed'), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tweetId')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('tweet')
    op.drop_table('channel')
    # ### end Alembic commands ###
